# Generated by Django 2.1.15 on 2023-11-28 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20231120_1458'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedidos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Moneda', models.CharField(max_length=50)),
                ('Solicitante', models.CharField(max_length=120)),
                ('Empresa', models.CharField(max_length=200)),
                ('Direccion', models.CharField(max_length=200)),
                ('Telefono', models.IntegerField(max_length=15)),
                ('Cantidad', models.IntegerField(max_length=50)),
                ('Detalles', models.CharField(max_length=400)),
            ],
        ),
    ]
