# Generated by Django 2.1.15 on 2023-11-28 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_pedidos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos',
            name='Cantidad',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='Telefono',
            field=models.IntegerField(),
        ),
    ]
